### ISSUE TITLE
If available, show the semver as well as the build version of the service

### ISSUE THREAD

**Issue by theskipster** [arbourd/concourse-slack-alert-resource#33]
It would be cool to see the version of the service with the build number instead of the concourse build number.

Instead of build number, it would be great to see the semver.buildnumber.

**Comment by hairyhenderson** [comment]
@theskipster this resource doesn't deploy services or anything, so there's no knowledge of a service's build number or anything... The only context this has is the concourse build number itself.

What _might_ be interesting though is for some method of reading the message from a file instead of the `message` parameter, so that another resource (such as one responsible for building or deploying something) could pass that information on to this resource.

**Comment by arbourd** [comment]
We could implement something similar to the [Slack Notification Resource](https://github.com/cloudfoundry-community/slack-notification-resource) where the message is actually a file, but something would need to generate that beforehand.

Either way, I don't think we would want to remove the concourse build number and job name for sure. That is how we track what Concourse task has failed, passed, etc.

**Comment by arbourd** [comment]
Closing in favor of #36.
