### ISSUE TITLE
put command

### ISSUE THREAD

**Issue by mybigopenbox** [arbourd/concourse-slack-alert-resource#83]
Hi
I believe there may be an issue with the out command
If you use the following even though a test channel exists it only send the message 'Tmessage' to the default channel

- put: slack
    params:
       text: "TCompleted"
       message: "MCompleted"
       alert_type: success
       color: "#eeeeee"
       channel: "test"

**Comment by pipeworks-asmith** [comment]
This is almost certainly because you're using the new "App" style webhooks instead of the legacy "Incoming Webhook" application. Slack's legacy apps can use an incoming webhook to talk to any channel, while its modern apps constrain a single webhook to using a single channel and ignores the "channel" value sent through the API.

**Comment by arbourd** [comment]
I'm going to close this for now because I think @pipeworks-asmith nailed it.

No need to support the app style stuff, especially as this project is in maintenance-ish mode.
